import "dotenv/config";

export const {
  USER_SECRET,
  MONGO_URL,
  WEBHOOK_SECRET,
  SENDGRID_KEY,
  FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CONFIG
} = {
  USER_SECRET: process.env.USER_SECRET,
  MONGO_URL: process.env.MONGO_URL,
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET,
  SENDGRID_KEY: process.env.SENDGRID_KEY,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
  FIREBASE_CONFIG: JSON.parse(process.env.FIREBASE_CONFIG)
};

export const PORT = process.env.PORT ?? 4000;
